USE vtrbank;

DROP TABLE IF EXISTS `User`;
DROP TABLE IF EXISTS `Account`;
DROP TABLE IF EXISTS `Logs`;

CREATE TABLE `User` (
	`Idx` INT NOT NULL PRIMARY KEY, # START AT 001, AUTO_INCREMENT 사용 안함
    `Name` CHAR(10) NOT NULL,
    `FRONT_PIN` INT NOT NULL, # 주민등록번호 앞자리
    `BACK_PIN` INT NOT NULL, # 주민등록번호 뒷자리
    `Date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) COMMENT = "유저의 정보를 담은 테이블";

CREATE TABLE `Account` (
	`Idx` INT NOT NULL PRIMARY KEY, # User 테이블과 같은 값 부여
    `Money` BIGINT NOT NULL DEFAULT 0,
    `Password` VARCHAR(255) NOT NULL, # 계좌 비밀번호
    FOREIGN KEY(`Idx`) REFERENCES `User`(`Idx`) ON UPDATE CASCADE ON DELETE RESTRICT
) COMMENT = "계좌 정보를 담은 테이블";

CREATE TABLE `Logs` (
	`Date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `Idx` INT NOT NULL PRIMARY KEY,
    `Message` VARCHAR(255) NOT NULL,
    FOREIGN KEY(`Idx`) REFERENCES `User`(`Idx`) ON UPDATE CASCADE ON DELETE RESTRICT
) COMMENT = "사용자 및 계좌 간 동작을 기록하는 테이블";